### PR TITLE
Language support

### PR DESCRIPTION
**Pull request by henhuy**
Uses [static-i18n](https://github.com/claudetech/node-static-i18n)

- [x] fix duplicate data-aos
- [x] check srcset vs data-srcset

### CODE REVIEW

**Comment by bmlancien** [comment]
@henhuy Can you help me with the correct command to use? Apparently it's not `static-i18n -l de -i de -i en pages`...

**Comment by henhuy** [comment]
put it already in the [Readme](https://github.com/rl-institut/WAM-Homepage/tree/feature/language)
It's:
`static-i18n -l de -i de -i en -o . pages/ `

**Comment by bmlancien** [comment]
I removed the `data-aos` duplicates, but I left the `srcset` vs `data-srcset` as it was, because I was not able to make it work properly. This concerns mostly the hero/header image. The other images are consistent on that matter.

I also added the EN translations, also to the `alt` attributes for images. And also "DE" and "EN" on the top navigation. You can change the paths in the json files in case they are not correct that way.

Can you also double check that I didn't miss or break anything by inserting the strings?

**Review by bmlancien — APPROVED** [review]

**Comment by henhuy** [comment]
Looks very good! Good work. THX will merge and upload

**Pull request merged**
